# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/myl',
                'doc_host': 'https://riversdark.github.io',
                'git_url': 'https://github.com/riversdark/myl',
                'lib_path': 'myl'},
  'syms': {'myl.core': {'myl.core.foo': ('core.html#foo', 'myl/core.py')}}}
